import React from 'react';
import Modal from '../common/Modal';
import { Printer, Shield, CheckCircle, FileText, Download } from 'lucide-react';

const PrintAgreementModal = ({ isOpen, onClose, agreement }) => {
  if (!agreement) return null;

  const handlePrint = () => {
    window.print();
  };

  const property = agreement.property || {};
  const owner = agreement.owner || {};
  const tenant = agreement.tenant || {};

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Rental Lease Agreement #${agreement.agreementNumber}`}
      maxWidth="850px"
      footer={
        <div style={{ display: 'flex', gap: '0.75rem', width: '100%', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
            *Platform-generated standard tenancy contract template
          </span>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button onClick={onClose} className="btn btn-secondary btn-sm">
              Close
            </button>
            <button onClick={handlePrint} className="btn btn-primary btn-sm">
              <Printer size={16} /> Print / Save as PDF
            </button>
          </div>
        </div>
      }
    >
      <div
        className="printable-agreement"
        style={{
          background: '#ffffff',
          color: '#0f172a',
          padding: '2.5rem',
          borderRadius: 'var(--radius-md)',
          fontFamily: 'Georgia, serif',
          lineHeight: '1.7',
          boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
        }}
      >
        {/* Header */}
        <div style={{ textAlign: 'center', borderBottom: '2px solid #0f172a', paddingBottom: '1.5rem', marginBottom: '1.5rem' }}>
          <h2 style={{ color: '#0f172a', fontSize: '1.6rem', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            Residential Lease Agreement
          </h2>
          <p style={{ color: '#64748b', fontSize: '0.85rem', marginTop: '0.25rem' }}>
            Agreement Reference ID: <strong>{agreement.agreementNumber}</strong> | Created: {new Date(agreement.createdAt).toLocaleDateString()}
          </p>
        </div>

        {/* Notice Disclaimer */}
        <div
          style={{
            background: '#f1f5f9',
            border: '1px solid #cbd5e1',
            borderRadius: '6px',
            padding: '0.75rem 1rem',
            marginBottom: '1.5rem',
            fontSize: '0.8rem',
            color: '#475569',
          }}
        >
          <strong>Notice:</strong> This document is a standardized tenancy agreement template generated by the UrbanNest Rental Management Platform. Both parties should verify that the clauses conform to local tenancy laws and state housing regulations.
        </div>

        {/* Parties Involved */}
        <div style={{ marginBottom: '1.5rem' }}>
          <h4 style={{ color: '#0f172a', fontSize: '1.1rem', fontWeight: 700, borderBottom: '1px solid #e2e8f0', paddingBottom: '0.4rem', marginBottom: '0.75rem' }}>
            1. PARTIES INVOLVED
          </h4>
          <p style={{ fontSize: '0.92rem' }}>
            This Residential Lease Agreement is entered into between:
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', marginTop: '0.75rem' }}>
            <div style={{ padding: '0.85rem', background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '6px' }}>
              <span style={{ fontSize: '0.75rem', fontWeight: 700, color: '#64748b', textTransform: 'uppercase' }}>LESSOR (OWNER / LANDLORD)</span>
              <p style={{ fontWeight: 700, fontSize: '1rem', color: '#0f172a', marginTop: '0.2rem' }}>{owner.name}</p>
              <p style={{ fontSize: '0.85rem', color: '#475569' }}>Email: {owner.email}</p>
              <p style={{ fontSize: '0.85rem', color: '#475569' }}>Phone: {owner.phone}</p>
              <p style={{ fontSize: '0.85rem', color: '#475569' }}>Address: {owner.address || 'Not specified'}</p>
            </div>
            <div style={{ padding: '0.85rem', background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '6px' }}>
              <span style={{ fontSize: '0.75rem', fontWeight: 700, color: '#64748b', textTransform: 'uppercase' }}>LESSEE (TENANT)</span>
              <p style={{ fontWeight: 700, fontSize: '1rem', color: '#0f172a', marginTop: '0.2rem' }}>{tenant.name}</p>
              <p style={{ fontSize: '0.85rem', color: '#475569' }}>Email: {tenant.email}</p>
              <p style={{ fontSize: '0.85rem', color: '#475569' }}>Phone: {tenant.phone}</p>
              <p style={{ fontSize: '0.85rem', color: '#475569' }}>Address: {tenant.address || 'Not specified'}</p>
            </div>
          </div>
        </div>

        {/* Leased Premises */}
        <div style={{ marginBottom: '1.5rem' }}>
          <h4 style={{ color: '#0f172a', fontSize: '1.1rem', fontWeight: 700, borderBottom: '1px solid #e2e8f0', paddingBottom: '0.4rem', marginBottom: '0.75rem' }}>
            2. LEASED PROPERTY PREMISES
          </h4>
          <p style={{ fontSize: '0.92rem' }}>
            The Lessor agrees to lease to the Lessee the residential premises situated at:
          </p>
          <div style={{ marginTop: '0.5rem', padding: '0.85rem', background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '6px' }}>
            <p style={{ fontWeight: 700, color: '#0f172a' }}>{property.title}</p>
            <p style={{ fontSize: '0.88rem', color: '#475569' }}>{property.address}, {property.city}, {property.state} - {property.pincode}</p>
            <p style={{ fontSize: '0.85rem', color: '#475569', marginTop: '0.3rem' }}>
              Specs: {property.bedrooms} BHK | {property.bathrooms} Baths | {property.area} sq ft | Furnishing: {property.furnishingStatus}
            </p>
          </div>
        </div>

        {/* Lease Term & Financials */}
        <div style={{ marginBottom: '1.5rem' }}>
          <h4 style={{ color: '#0f172a', fontSize: '1.1rem', fontWeight: 700, borderBottom: '1px solid #e2e8f0', paddingBottom: '0.4rem', marginBottom: '0.75rem' }}>
            3. LEASE TERM & FINANCIAL OBLIGATIONS
          </h4>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.9rem', marginTop: '0.5rem' }}>
            <tbody>
              <tr style={{ borderBottom: '1px solid #e2e8f0' }}>
                <td style={{ padding: '0.5rem 0', fontWeight: 600, color: '#64748b' }}>Lease Duration:</td>
                <td style={{ padding: '0.5rem 0', color: '#0f172a', fontWeight: 700 }}>
                  {new Date(agreement.startDate).toLocaleDateString()} to {new Date(agreement.endDate).toLocaleDateString()}
                </td>
              </tr>
              <tr style={{ borderBottom: '1px solid #e2e8f0' }}>
                <td style={{ padding: '0.5rem 0', fontWeight: 600, color: '#64748b' }}>Monthly Rent:</td>
                <td style={{ padding: '0.5rem 0', color: '#0f172a', fontWeight: 700 }}>
                  ₹{agreement.monthlyRent?.toLocaleString()} (Due on or before the {agreement.dueDate || 5}th of each month)
                </td>
              </tr>
              <tr style={{ borderBottom: '1px solid #e2e8f0' }}>
                <td style={{ padding: '0.5rem 0', fontWeight: 600, color: '#64748b' }}>Refundable Security Deposit:</td>
                <td style={{ padding: '0.5rem 0', color: '#0f172a', fontWeight: 700 }}>
                  ₹{agreement.securityDeposit?.toLocaleString()}
                </td>
              </tr>
              <tr>
                <td style={{ padding: '0.5rem 0', fontWeight: 600, color: '#64748b' }}>Agreement Status:</td>
                <td style={{ padding: '0.5rem 0', color: '#059669', fontWeight: 700, textTransform: 'uppercase' }}>
                  {agreement.status}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Terms & Clauses */}
        <div style={{ marginBottom: '2rem' }}>
          <h4 style={{ color: '#0f172a', fontSize: '1.1rem', fontWeight: 700, borderBottom: '1px solid #e2e8f0', paddingBottom: '0.4rem', marginBottom: '0.75rem' }}>
            4. COVENANTS AND SPECIAL CONDITIONS
          </h4>
          <div style={{ whiteSpace: 'pre-line', fontSize: '0.88rem', color: '#334155', background: '#f8fafc', padding: '1rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
            {agreement.terms}
          </div>
        </div>

        {/* Signatures */}
        <div style={{ marginTop: '2.5rem', paddingTop: '1.5rem', borderTop: '2px solid #0f172a' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '3rem' }}>
            <div>
              <p style={{ fontSize: '0.85rem', color: '#64748b', marginBottom: '0.5rem' }}>Lessor (Landlord) Signature:</p>
              <div style={{ fontFamily: 'cursive', fontSize: '1.4rem', color: '#4f46e5', borderBottom: '1px solid #94a3b8', paddingBottom: '0.5rem', minHeight: '40px' }}>
                {agreement.ownerSignature?.signed ? agreement.ownerSignature.signedBy : '[Pending Signature]'}
              </div>
              <p style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '0.35rem' }}>
                Digitally Authenticated: {agreement.ownerSignature?.signedAt ? new Date(agreement.ownerSignature.signedAt).toLocaleString() : 'N/A'}
              </p>
            </div>

            <div>
              <p style={{ fontSize: '0.85rem', color: '#64748b', marginBottom: '0.5rem' }}>Lessee (Tenant) Signature:</p>
              <div style={{ fontFamily: 'cursive', fontSize: '1.4rem', color: '#0ea5e9', borderBottom: '1px solid #94a3b8', paddingBottom: '0.5rem', minHeight: '40px' }}>
                {agreement.tenantSignature?.signed ? agreement.tenantSignature.signedBy : '[Pending Signature]'}
              </div>
              <p style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '0.35rem' }}>
                Digitally Authenticated: {agreement.tenantSignature?.signedAt ? new Date(agreement.tenantSignature.signedAt).toLocaleString() : 'N/A'}
              </p>
            </div>
          </div>
        </div>
      </div>
    </Modal>
  );
};

export default PrintAgreementModal;
